version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"  # Expose le backend sur le port 8080
    networks:
      - app-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/brikol
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_MAIL_HOST=localhost
      - SPRING_MAIL_PORT=1025
    depends_on:
      - db

  frontend:
    build:
      context: ./brikool-frontend
    ports:
      - "3000:3000"  # Expose le frontend sur le port 3000
    networks:
      - app-network
    environment:
      - NODE_ENV=production

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brikol
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:
    driver: local

networks:
  app-network:
    driver: bridge
